const menuData = [
  // FOODS
  {
    name: "Kelewele",
    price: "GH₵ 45",
    desc: "Spicy fried plantain cubes seasoned with ginger, pepper, and local spices.",
    category: "Appetizers",
    type: "food",
  },
  {
    name: "Beef Chichinga",
    price: "GH₵ 60",
    desc: "Spicy suya-spiced beef kebabs grilled to perfection with onions.",
    category: "Appetizers",
    type: "food",
  },
  {
    name: "Jollof Royal",
    price: "GH₵ 120",
    desc: "Signature smoky jasmine rice with grilled chicken, coleslaw, and shito.",
    category: "Mains",
    type: "food",
  },
  {
    name: "Banku & Tilapia",
    price: "GH₵ 135",
    desc: "Fermented corn dough, whole grilled tilapia, fresh pepper sauce.",
    category: "Mains",
    type: "food",
  },
  {
    name: "Fufu & Goat Light Soup",
    price: "GH₵ 110",
    desc: "Pounded cassava/plantain in spicy, aromatic goat meat soup.",
    category: "Mains",
    type: "food",
  },
  {
    name: "Red Red",
    price: "GH₵ 95",
    desc: "Savory black-eyed pea stew with palm oil and soft fried plantains.",
    category: "Mains",
    type: "food",
  },
  {
    name: "Fried Yam Chips",
    price: "GH₵ 40",
    desc: "Served with spicy turkey tail (Tsofi) or pepper sauce.",
    category: "Sides",
    type: "food",
  },
  {
    name: "Waakye",
    price: "GH₵ 85",
    desc: "Rice and beans with millet leaves, gari, and spaghetti.",
    category: "Sides",
    type: "food",
  },
  {
    name: "Tropical Fruit Platter",
    price: "GH₵ 55",
    desc: "Seasonal selection of fresh papaya, pineapple, and mango.",
    category: "Desserts",
    type: "food",
  },
  {
    name: "Sobolo Sorbet",
    price: "GH₵ 45",
    desc: "Refreshing frozen treat made from spiced hibiscus flowers.",
    category: "Desserts",
    type: "food",
  },

  // DRINKS
  {
    name: "Sobolo",
    price: "GH₵ 25",
    desc: "Hibiscus & Ginger juice, chilled.",
    category: "Juices",
    type: "drink",
  },
  {
    name: "Asaana",
    price: "GH₵ 25",
    desc: "Spiced caramelized corn drink with milk.",
    category: "Juices",
    type: "drink",
  },
  {
    name: "Fresh Pineapple",
    price: "GH₵ 30",
    desc: "Pressed fresh daily.",
    category: "Juices",
    type: "drink",
  },
  {
    name: "Alvaro / Malta",
    price: "GH₵ 20",
    desc: "Local favorites.",
    category: "Soft Drinks",
    type: "drink",
  },
  {
    name: "Coca-Cola / Fanta",
    price: "GH₵ 15",
    desc: "Classic sodas.",
    category: "Soft Drinks",
    type: "drink",
  },
  {
    name: "Ghana Hot Chocolate",
    price: "GH₵ 35",
    desc: "Rich cocoa from the region.",
    category: "Hot Beverages",
    type: "drink",
  },
  {
    name: "Citronella Tea",
    price: "GH₵ 25",
    desc: "Lemon grass infusion.",
    category: "Hot Beverages",
    type: "drink",
  },
  {
    name: "Club Beer",
    price: "GH₵ 25",
    desc: "Large bottle, perfectly chilled.",
    category: "Alcoholic Options",
    type: "drink",
  },
  {
    name: "Palm Wine",
    price: "GH₵ 30",
    desc: "Fresh tapped (seasonal).",
    category: "Alcoholic Options",
    type: "drink",
  },
  {
    name: "Orijin",
    price: "GH₵ 25",
    desc: "Herbal alcoholic beverage.",
    category: "Alcoholic Options",
    type: "drink",
  },
];

export default menuData